// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { nurixChatBlock } from "./index";

export const nurixChatBlockSchema = parseBlockSchema(nurixChatBlock);
export const nurixChatCredentialsSchema = parseBlockCredentials(
  nurixChatBlock.id,
  auth,
);
